import Foundation

enum ClipboardPrivacyPolicy {
    static let concealedPasteboardTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword"
    ]

    static let commonSensitiveBundleIdentifiers: Set<String> = [
        "com.1password.1password",
        "com.agilebits.onepassword7",
        "com.apple.keychainaccess",
        "com.bitwarden.desktop",
        "com.googlecode.iterm2",
        "com.lastpass.lastpass",
        "com.mitchellh.ghostty",
        "com.github.wez.wezterm",
        "com.apple.terminal",
        "org.alacritty"
    ]

    static func shouldCapture(
        sourceBundleIdentifier: String?,
        pasteboardTypes: [String],
        isPaused: Bool,
        excludesCommonSensitiveApps: Bool,
        customExcludedBundleIdentifiers: Set<String>
    ) -> Bool {
        guard !isPaused else { return false }
        let normalizedTypes = Set(pasteboardTypes.map { $0.lowercased() })
        guard concealedPasteboardTypes.allSatisfy({
            !normalizedTypes.contains($0.lowercased())
        }) else {
            return false
        }

        guard let sourceBundleIdentifier = sourceBundleIdentifier?.lowercased() else {
            return true
        }
        let customExcluded = Set(customExcludedBundleIdentifiers.map { $0.lowercased() })
        guard !customExcluded.contains(sourceBundleIdentifier) else { return false }
        if excludesCommonSensitiveApps,
           commonSensitiveBundleIdentifiers.contains(sourceBundleIdentifier) {
            return false
        }
        return true
    }

    static func bundleIdentifiers(from text: String) -> Set<String> {
        Set(
            text
                .components(separatedBy: CharacterSet.whitespacesAndNewlines.union(
                    CharacterSet(charactersIn: ",;")
                ))
                .map { $0.trimmingCharacters(in: .whitespacesAndNewlines).lowercased() }
                .filter { !$0.isEmpty }
        )
    }
}
